### ISSUE TITLE
Progressive Missile Pods (Battlecruiser) does not list damage amounts 

### ISSUE THREAD

**Issue by golizar** [MatthewMarinets/ap_sc2_icons#1]
I thought it might be useful to list that level 1 does 40 (+50 vs light) and level 2 does 110 to all air units in the area. Not a huge issue, but the others I've seen list what each progression level does.

**Comment by MatthewMarinets** [comment]
Updated, already went live. Double-checking the mod data, I also notice the energy cost is 125 for level 1 and 50 less for level 2. Going to just add a note "... and costs less energy" and I'll call it done.

**Comment by MatthewMarinets** [comment]
Pushed, should be live in the next few seconds. Thanks for the feedback!
